In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
d=np.ones((2,2))
print(d)

[[1. 1.]
 [1. 1.]]


In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [7]:
c=a+b
print(c)

[5 7 9]


In [8]:
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
f=d*e
print(f)

[[ 5 12]
 [21 32]]


In [9]:
i=np.dot(d,e)
print(i)

[[19 22]
 [43 50]]
